-- Almmatix OS Supabase Complete Schema Seeding Script
-- Paste this script directly into the Supabase SQL Editor of your new project.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Clean existing entities
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.releases CASCADE;
DROP TABLE IF EXISTS public.internal_tasks CASCADE;
DROP TABLE IF EXISTS public.project_flags CASCADE;
DROP TABLE IF EXISTS public.outreach_leads CASCADE;
DROP TABLE IF EXISTS public.activities CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.internal_products CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.authorized_emails CASCADE;

DROP TYPE IF EXISTS client_stage CASCADE;
DROP TYPE IF EXISTS client_category CASCADE;
DROP TYPE IF EXISTS outreach_status CASCADE;
DROP TYPE IF EXISTS lead_source CASCADE;
DROP TYPE IF EXISTS flag_severity CASCADE;
DROP TYPE IF EXISTS flag_status CASCADE;
DROP TYPE IF EXISTS task_status CASCADE;
DROP TYPE IF EXISTS release_status CASCADE;

-- Create Custom Enums
CREATE TYPE client_stage AS ENUM ('Lead', 'Proposal', 'In Dev', 'Active', 'Completed');
CREATE TYPE client_category AS ENUM ('Potential', 'Ongoing');
CREATE TYPE outreach_status AS ENUM ('Lead', 'Cold Contact', 'Discussion', 'Proposal', 'Converted', 'Lost');
CREATE TYPE lead_source AS ENUM ('Cold Call', 'LinkedIn', 'Twitter', 'Email', 'Referral', 'Instagram', 'Social Media');
CREATE TYPE flag_severity AS ENUM ('Critical', 'High', 'Medium', 'Low');
CREATE TYPE flag_status AS ENUM ('Open', 'Investigating', 'In Dev', 'Resolved');
CREATE TYPE task_status AS ENUM ('Todo', 'In Progress', 'In Review', 'Resolved');
CREATE TYPE release_status AS ENUM ('Draft', 'Awaiting Review', 'Approved');

-- 1. Profiles Table (Extends Supabase Auth)
CREATE TABLE public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name text NOT NULL,
    role text,
    category text NOT NULL CHECK (category IN ('admin', 'client')),
    avatar text,
    color_var text,
    primary_focus text,
    responsibilities text[] DEFAULT '{}'::text[],
    active_tasks text[] DEFAULT '{}'::text[],
    created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-access to profiles"
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Allow profiles update for owners"
    ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow admin full access to profiles"
    ON public.profiles FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

-- 2. Clients Table
CREATE TABLE public.clients (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profile_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    name text NOT NULL,
    project text NOT NULL,
    location text,
    category client_category NOT NULL DEFAULT 'Ongoing',
    stage client_stage NOT NULL DEFAULT 'In Dev',
    health integer DEFAULT 100,
    revenue bigint DEFAULT 0,
    last_activity text,
    avatar text,
    assigned_admin_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins have full access to clients"
    ON public.clients FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

CREATE POLICY "Clients can view their own client profile"
    ON public.clients FOR SELECT USING (
        profile_id = auth.uid() OR 
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

-- 3. Internal Products Table
CREATE TABLE public.internal_products (
    id text PRIMARY KEY,
    name text NOT NULL,
    stage text NOT NULL,
    progress integer DEFAULT 0,
    description text,
    lead_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    repo_link text,
    sandbox_link text,
    metrics jsonb DEFAULT '{"label": "Sprint Velocity", "value": "0 pts/wk"}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.internal_products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins have full access to products"
    ON public.internal_products FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

CREATE POLICY "Clients can read products"
    ON public.internal_products FOR SELECT USING (true);

-- 4. Comments Table
CREATE TABLE public.comments (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    author text NOT NULL,
    role text CHECK (role IN ('admin', 'client')),
    text text NOT NULL,
    timestamp text,
    time_elapsed text,
    client_id integer REFERENCES public.clients(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins have full access to comments"
    ON public.comments FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

CREATE POLICY "Clients can read and create comments for their sandbox"
    ON public.comments FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.clients 
            WHERE clients.id = comments.client_id AND clients.profile_id = auth.uid()
        )
    );

-- 5. Activities Table
CREATE TABLE public.activities (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    action text NOT NULL,
    client text,
    time text,
    type text CHECK (type IN ('milestone', 'comment', 'invoice', 'alert')),
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can view and edit activities"
    ON public.activities FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

CREATE POLICY "Clients can view activities related to their project"
    ON public.activities FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.clients 
            WHERE clients.name = activities.client AND clients.profile_id = auth.uid()
        )
    );

-- 6. Outreach Leads Table
CREATE TABLE public.outreach_leads (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    company_name text NOT NULL,
    project_description text,
    source lead_source NOT NULL,
    status outreach_status NOT NULL,
    estimated_value bigint DEFAULT 0,
    assigned_admin_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    calls_made integer DEFAULT 0,
    notes text[] DEFAULT '{}'::text[],
    last_contacted text,
    sourced_by_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    engagement_score integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.outreach_leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins have full access to outreach leads"
    ON public.outreach_leads FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

-- 7. Project Flags Table
CREATE TABLE public.project_flags (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id integer REFERENCES public.clients(id) ON DELETE CASCADE,
    title text NOT NULL,
    description text,
    severity flag_severity NOT NULL,
    status flag_status NOT NULL,
    created_at text,
    assigned_admin_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    resolution_notes text,
    sprint_logs jsonb DEFAULT '[]'::jsonb,
    db_created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.project_flags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins have full access to project flags"
    ON public.project_flags FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

CREATE POLICY "Clients have access to their own project flags"
    ON public.project_flags FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.clients 
            WHERE clients.id = project_flags.client_id AND clients.profile_id = auth.uid()
        )
    );

-- 8. Internal Tasks Table
CREATE TABLE public.internal_tasks (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id integer REFERENCES public.clients(id) ON DELETE SET NULL,
    product_id text REFERENCES public.internal_products(id) ON DELETE SET NULL,
    title text NOT NULL,
    assigned_admin_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    status task_status NOT NULL DEFAULT 'Todo',
    origin_comment_id text,
    internal_notes text[] DEFAULT '{}'::text[],
    created_at text,
    db_created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.internal_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins have full access to internal tasks"
    ON public.internal_tasks FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

-- 9. Releases Table
CREATE TABLE public.releases (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id integer REFERENCES public.clients(id) ON DELETE CASCADE,
    version text NOT NULL,
    title text NOT NULL,
    what_was_improved text[] DEFAULT '{}'::text[],
    published_at text,
    status release_status NOT NULL DEFAULT 'Draft',
    approved_at text,
    release_notes text,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.releases ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins have full access to releases"
    ON public.releases FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

CREATE POLICY "Clients can view their project releases"
    ON public.releases FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.clients 
            WHERE clients.id = releases.client_id AND clients.profile_id = auth.uid()
        )
    );

-- 10. Credentials Provisioning (Pre-Authorization table)
CREATE TABLE public.authorized_emails (
    email text PRIMARY KEY,
    name text NOT NULL,
    role text,
    category text NOT NULL CHECK (category IN ('admin', 'client')),
    avatar text,
    color_var text,
    primary_focus text,
    responsibilities text[] DEFAULT '{}'::text[],
    active_tasks text[] DEFAULT '{}'::text[],
    client_id integer,
    created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.authorized_emails ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins have full access to authorized emails"
    ON public.authorized_emails FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE id = auth.uid() AND category = 'admin'
        )
    );

CREATE POLICY "Allow public select on authorized emails during signup"
    ON public.authorized_emails FOR SELECT USING (true);

-- 11. Triggers for Automatic Profile Creation on Signup (Incorporating Pre-Authorization Lookup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  pre_auth RECORD;
BEGIN
  -- Check if email is pre-authorized
  SELECT * INTO pre_auth FROM public.authorized_emails WHERE LOWER(email) = LOWER(new.email);

  IF pre_auth.email IS NOT NULL THEN
    -- Match account with pre-authorized parameters
    INSERT INTO public.profiles (
      id, 
      name, 
      role, 
      category, 
      avatar, 
      color_var, 
      primary_focus,
      responsibilities,
      active_tasks
    )
    VALUES (
      new.id,
      pre_auth.name,
      pre_auth.role,
      pre_auth.category,
      pre_auth.avatar,
      pre_auth.color_var,
      pre_auth.primary_focus,
      pre_auth.responsibilities,
      pre_auth.active_tasks
    );

    -- If client profile, dynamically link it to their pre-assigned clients project
    IF pre_auth.category = 'client' AND pre_auth.client_id IS NOT NULL THEN
      UPDATE public.clients 
      SET profile_id = new.id 
      WHERE id = pre_auth.client_id;
    END IF;

  ELSE
    -- Automatic registration default for the 4 core partner credentials
    INSERT INTO public.profiles (
      id, 
      name, 
      role, 
      category, 
      avatar, 
      color_var, 
      primary_focus,
      responsibilities,
      active_tasks
    )
    VALUES (
      new.id,
      CASE 
        WHEN new.email = 'lakshbetala15@gmail.com' THEN 'Lakshya'
        WHEN new.email = 'gandhimouriyan1234@gmail.com' THEN 'Mouriyan'
        WHEN new.email = 'monarchankit25@gmail.com' THEN 'Ankit'
        WHEN new.email = 'muskanabani01@gmail.com' THEN 'Muskan'
        ELSE COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1))
      END,
      CASE 
        WHEN new.email = 'lakshbetala15@gmail.com' THEN 'PM & Client Delivery Lead'
        WHEN new.email = 'gandhimouriyan1234@gmail.com' THEN 'Backend & Tech Delivery Lead'
        WHEN new.email = 'monarchankit25@gmail.com' THEN 'Outreach & Marketing Lead'
        WHEN new.email = 'muskanabani01@gmail.com' THEN 'Brand & Marketing Director'
        ELSE 'Client Partner'
      END,
      CASE 
        WHEN new.email IN (
          'lakshbetala15@gmail.com', 
          'gandhimouriyan1234@gmail.com', 
          'monarchankit25@gmail.com', 
          'muskanabani01@gmail.com'
        ) THEN 'admin' 
        ELSE 'client' 
      END,
      CASE 
        WHEN new.email = 'lakshbetala15@gmail.com' THEN 'LB'
        WHEN new.email = 'gandhimouriyan1234@gmail.com' THEN 'MR'
        WHEN new.email = 'monarchankit25@gmail.com' THEN 'AK'
        WHEN new.email = 'muskanabani01@gmail.com' THEN 'MK'
        ELSE UPPER(SUBSTRING(COALESCE(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)) FROM 1 FOR 2))
      END,
      CASE 
        WHEN new.email = 'lakshbetala15@gmail.com' THEN 'var(--color-admin-lakshya)'
        WHEN new.email = 'gandhimouriyan1234@gmail.com' THEN 'var(--color-admin-mouriyan)'
        WHEN new.email = 'monarchankit25@gmail.com' THEN 'var(--color-admin-ankit)'
        WHEN new.email = 'muskanabani01@gmail.com' THEN 'var(--color-admin-muskan)'
        ELSE 'var(--color-neutral)'
      END,
      CASE 
        WHEN new.email IN ('lakshbetala15@gmail.com', 'gandhimouriyan1234@gmail.com') THEN 'Client Delivery'
        WHEN new.email IN ('monarchankit25@gmail.com', 'muskanabani01@gmail.com') THEN 'Outreach & Marketing'
        ELSE 'Product Sandbox'
      END,
      CASE 
        WHEN new.email = 'lakshbetala15@gmail.com' THEN ARRAY['Client Communication', 'Product Strategy', 'QA / Delivery Gate']
        WHEN new.email = 'gandhimouriyan1234@gmail.com' THEN ARRAY['API Architecture', 'Database Schema', 'Production Builds']
        WHEN new.email = 'monarchankit25@gmail.com' THEN ARRAY['Lead Sourcing', 'Cold Calling Funnel', 'Client Accounts']
        WHEN new.email = 'muskanabani01@gmail.com' THEN ARRAY['UI/UX Design Sprints', 'Brand Assets', 'Social Media Branding']
        ELSE ARRAY[]::text[]
      END,
      CASE 
        WHEN new.email = 'lakshbetala15@gmail.com' THEN ARRAY['Review Supreme Petro Release', 'Rafter.so Onboarding']
        WHEN new.email = 'gandhimouriyan1234@gmail.com' THEN ARRAY['Supabase Auth Setup', 'BI Database Performance Optimization']
        WHEN new.email = 'monarchankit25@gmail.com' THEN ARRAY['Karthik Exports Pitch Deck', 'Social Media Leads Sourcing']
        WHEN new.email = 'muskanabani01@gmail.com' THEN ARRAY['NJ Jewellers Price Board UI', 'Almmatix Marketing Banners']
        ELSE ARRAY[]::text[]
      END
    );
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 12. Initial Database Seed Values for Non-Relational Fields
INSERT INTO public.internal_products (id, name, stage, progress, description, repo_link, sandbox_link, metrics)
VALUES 
  ('p1', 'Almmatix CRM Core', 'Beta', 85, 'Our proprietary internal management tool and Agency OS.', 'github.com/almmatix/crm-core', 'almmatix.com/sandbox/crm', '{"label": "Sprint Velocity", "value": "9.2 pts/wk"}'),
  ('p2', 'Design System V2', 'Planning', 20, 'Unified component library for fast shipping.', 'github.com/almmatix/design-v2', NULL, '{"label": "Total Components", "value": "48 assets"}'),
  ('p3', 'Supabase Boilerplate', 'In Dev', 40, 'Quickstart backend template for SaaS projects.', 'github.com/almmatix/supabase-starter', 'supabase-starter.almmatix.com', '{"label": "Active Integrations", "value": "6 engines"}');
